### ISSUE TITLE
create easier to access scripts path

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/RunLast#1]
maybe [/scripts/runlast/]?

**Comment by Sokrates1989** [comment]
currently the cd link to go to scripts directory does not even (did not for me) work: cd $(getcfg RunLast Scripts_Path -f /etc/config/qpkg.conf)

Looking at /etc/config/qpkg.conf file: It had no key "Scripts_Path" for App RunLast, but it had a "Install_Path" key under which I found the scripts DIR.

**Comment by OneCDOnly** [comment]
Hey @Sokrates1989. :)

Hmm, are you using an older version of the RunLast QPKG? I added those new keys back in April 2022.

**Comment by Sokrates1989** [comment]
<stroke>Yeah, I just downloaded and installed it</stroke>
UPDATE: No I did not have the most current version. I installed RunLast through https://www.qnapclub.eu/en/repo.xml this time.

However, it could be an issue with my qnap as well.. I also get the Could not chdir to home directory /share/homes/xxxx: No such file or directory after every restart, since I completely set up my NAS again. I had to change volume from thin volume, beause there were too many errors and the system forced me to run file system checks, almost every day. Now I changed to thick volume and have this.. *sigh*

When I installed RunLast with the Thin Volume setup it worked with the cd $(getcfg RunLast Scripts_Path -f /etc/config/qpkg.conf

If you made no changes within the last 6 weeks, it is my NAS, that is causing the issue..

**Comment by Sokrates1989** [comment]
Forgive my rudeness. Thanks for the very quick reply. I guess I was just shocked^^

BTW: Thanks to this package I can make sure that all my docker-compose volumes run even after any (unwanted) restart. Awesome work! Thank you very much.

**Comment by Sokrates1989** [comment]
Here is the output, for the /etc/config/qpkg.conf for RunLast. I now see, that I have the older version.
My bad very much. I am so sorry. I installed RunLast this time through the App Center after having added the qnap club repo https://www.qnapclub.eu/en/repo.xml. Guess here is still the version 210809 marked as latest. I used the direct download a few weeks ago, I guess.

[RunLast]
Name = RunLast
Class = null
Status = complete
store = e754538ad86a655a0687f76c5190a5f8
Build = 20210809
Display_Name = RunLast (CLI)
Version = 210809
Author = OneCD
QPKG_File = RunLast.qpkg
Date = 2022-07-04
Shell = /share/CACHEDEV1_DATA/.qpkg/RunLast/runlast.sh
Install_Path = /share/CACHEDEV1_DATA/.qpkg/RunLast
WebUI = /RunLast.log
RC_Number = 999
Desktop = 1
FW_Ver_Min = 4.0.0
Web_Port = 8080
Enable = TRUE

**Comment by OneCDOnly** [comment]
Yup, sorry - I don't distribute via the Qnapclub anymore. So, the version available on that repo is out-of-date. You'd need to download the latest one from the build directory here: https://github.com/OneCDOnly/RunLast/tree/main/build

The most recent version at the moment is 220426.

**Comment by Sokrates1989** [comment]
No problem, it was my bad to begin with.
