### ISSUE TITLE
RunLast blocks drive decryption

### ISSUE THREAD

**Issue by Kurisutian** [OneCDOnly/RunLast#11]
If installed RunLast on a TVS-873e with the latest QTS5 version installed. Got all disks encrypted so after Trevor they need to be decrypted first to start everything. Also SortMyPkg is installed. I needed RunLast to start Caddy's at boot for using it as a reverse proxy. 
When decrypting the disks they get stuck at 69% and RunLast is stuck at in starting state. Only when cancelling RunLast the decryption continues to total decryption. Of course carry then does not start automatically. Even worse, when not cancelling RunLast after a few minutes the NAS becomes unavailable in the network (which might be something else maybe but when running through with the encryption it remains available). I've tested it several times and every time it's the same thing, decryption is stuck until I cancel the RunLast app start in the application manager. 
The only init style startup script I use is the caddy one which I modified for the proper reverse proxy start. It all starts when running it manually so the script is fine as well.

**Comment by OneCDOnly** [comment]
Hi @Kurisutian :)

When RunLast appears to have stalled, it's because its waiting for one of your user scripts to exit. You'll need to find which one is hanging. Make use of RunLast's log file, and don't be shy about making your scripts create their own logs too. 

Launching a daemon that doesn't disconnect from the current tty is probably the most likely cause of a hanging condition. 

**Important note:** the QTS environment _during_ startup (when RunLast executes your scripts) is also not the same as _after_ startup has completed. A script may work just fine when run manually at the CLI, but throw errors when running via RunLast due to not being attached to a terminal, $PATH incorrect, binaries unavailable, etc... 

There's not-a-lot I can do to ensure RunLast completes startup with a hanging user script, except to background all script jobs. This won't fix your issue however. Your script would still contain a condition causing it to stall or fail to exit. 

Hope this helps. I really should create a wiki page for this info.
